services:
  #We can change service name later
  pallets-api:
    user: root
    container_name: pallets-api
    working_dir: /app
    network_mode: host
    build: .
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: unless-stopped
    tty: true
    network_mode: host
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
