version: '3.8'
services:
  #We can change service name later
  palets-api:
    user: root
    container_name: palets-api
    working_dir: /app
    build: .''
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
