version: '3'
services:
  #We can change service name later
  palets-api:
    user: root
    container_name: palets-api
    build: .
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/home/node/app
    network_mode: host
    depends_on:
      - db

  db:
    image: postgres:16.2
    container_name: palets-db
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    network_mode: host

volumes:
  dbdata:
    driver: local
